// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/judge/v1alpha1/policy.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Statement_Effect int32

const (
	Statement_ALLOW Statement_Effect = 0
	Statement_DENY  Statement_Effect = 1
)

var Statement_Effect_name = map[int32]string{
	0: "ALLOW",
	1: "DENY",
}

var Statement_Effect_value = map[string]int32{
	"ALLOW": 0,
	"DENY":  1,
}

func (x Statement_Effect) String() string {
	return proto.EnumName(Statement_Effect_name, int32(x))
}

func (Statement_Effect) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{1, 0}
}

// A Judge policy.
type Policy struct {
	// Output only. The object resource name of the document, for example
	// `orn:judge-org:judge-service::policy/default_policy`.
	PolicyId string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	// Name element specifies a user friendly name for the policy.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description element specifies description/usage about the policy.
	//
	// Optional.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Statement contains a list of Statement.
	//
	// Optional.
	Statements []*Statement `protobuf:"bytes,4,rep,name=statements,proto3" json:"statements,omitempty"`
	// Output only. The time at which the policy was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time at which the document was last changed.
	//
	// This value is initally set to the `create_time` then increases
	// monotonically with each change to the policy.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{0}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetStatements() []*Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *Policy) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Policy) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

// An Statement.
type Statement struct {
	// The Effect element is required and specifies whether the statement
	// results in an allow or an explicit deny. Valid values for Effect are
	// Allow and Deny.
	Effect Statement_Effect `protobuf:"varint,1,opt,name=effect,proto3,enum=judge.api.v1alpha1.Statement_Effect" json:"effect,omitempty"`
	// The Action element describes the specific action or actions that will
	// be allowed or denied.
	Actions []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// The Resource element specifies the object or objects that the statement
	// covers.
	Resources []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	// The Conditions element contains definition of conditions to execute.
	Conditions           []string `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{1}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetEffect() Statement_Effect {
	if m != nil {
		return m.Effect
	}
	return Statement_ALLOW
}

func (m *Statement) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Statement) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *Statement) GetConditions() []string {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func init() {
	proto.RegisterEnum("judge.api.v1alpha1.Statement_Effect", Statement_Effect_name, Statement_Effect_value)
	proto.RegisterType((*Policy)(nil), "judge.api.v1alpha1.Policy")
	proto.RegisterType((*Statement)(nil), "judge.api.v1alpha1.Statement")
}

func init() { proto.RegisterFile("api/judge/v1alpha1/policy.proto", fileDescriptor_187ca9f6326818cb) }

var fileDescriptor_187ca9f6326818cb = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x8b, 0xd4, 0x30,
	0x14, 0xc6, 0xed, 0xb4, 0x5b, 0xb7, 0xaf, 0x20, 0x4b, 0x4e, 0x61, 0x75, 0xdd, 0x32, 0x78, 0xe8,
	0x29, 0x75, 0xeb, 0x51, 0x3d, 0x28, 0xee, 0x41, 0x58, 0x54, 0xaa, 0x20, 0x7a, 0x19, 0x32, 0xe9,
	0x9b, 0x4e, 0x74, 0xda, 0x84, 0x24, 0x1d, 0xf0, 0xff, 0xf0, 0x0f, 0xf2, 0x4f, 0x93, 0x26, 0xd3,
	0x71, 0x40, 0xd0, 0x5b, 0xfb, 0x7d, 0xdf, 0x2f, 0x79, 0xdf, 0x23, 0x70, 0xcd, 0xb5, 0xac, 0xbe,
	0x8d, 0x6d, 0x87, 0xd5, 0xfe, 0x86, 0xef, 0xf4, 0x96, 0xdf, 0x54, 0x5a, 0xed, 0xa4, 0xf8, 0xc1,
	0xb4, 0x51, 0x4e, 0x11, 0xe2, 0x4d, 0xc6, 0xb5, 0x64, 0x73, 0xe0, 0xf2, 0xba, 0x53, 0xaa, 0xdb,
	0x61, 0xe5, 0x13, 0xeb, 0x71, 0x53, 0x39, 0xd9, 0xa3, 0x75, 0xbc, 0xd7, 0x01, 0x5a, 0xfe, 0x5c,
	0x40, 0xfa, 0xc1, 0x9f, 0x42, 0x1e, 0x42, 0x16, 0xce, 0x5b, 0xc9, 0x96, 0x46, 0x45, 0x54, 0x66,
	0xcd, 0x79, 0x10, 0xde, 0xb6, 0x84, 0x40, 0x32, 0xf0, 0x1e, 0xe9, 0xc2, 0xeb, 0xfe, 0x9b, 0x14,
	0x90, 0xb7, 0x68, 0x85, 0x91, 0xda, 0x49, 0x35, 0xd0, 0xd8, 0x5b, 0xa7, 0x12, 0x79, 0x09, 0x60,
	0x1d, 0x77, 0xd8, 0xe3, 0xe0, 0x2c, 0x4d, 0x8a, 0xb8, 0xcc, 0xeb, 0x2b, 0xf6, 0xf7, 0x9c, 0xec,
	0xe3, 0x9c, 0x6a, 0x4e, 0x00, 0xf2, 0x1c, 0x72, 0x61, 0x90, 0x3b, 0x5c, 0x4d, 0x63, 0xd3, 0xb3,
	0x22, 0x2a, 0xf3, 0xfa, 0x92, 0x85, 0x4e, 0x6c, 0xee, 0xc4, 0x3e, 0xcd, 0x9d, 0x1a, 0x08, 0xf1,
	0x49, 0x98, 0xe0, 0x51, 0xb7, 0x47, 0x38, 0xfd, 0x3f, 0x1c, 0xe2, 0x93, 0xb0, 0xfc, 0x15, 0x41,
	0x76, 0x9c, 0x89, 0xbc, 0x80, 0x14, 0x37, 0x1b, 0x14, 0xce, 0xaf, 0xe5, 0x41, 0xfd, 0xe4, 0x9f,
	0x15, 0xd8, 0xad, 0xcf, 0x36, 0x07, 0x86, 0x50, 0xb8, 0xcf, 0xc5, 0xb4, 0x0e, 0x4b, 0x17, 0x45,
	0x5c, 0x66, 0xcd, 0xfc, 0x4b, 0x1e, 0x41, 0x66, 0xd0, 0xaa, 0xd1, 0x08, 0xb4, 0x34, 0xf6, 0xde,
	0x1f, 0x81, 0x3c, 0x06, 0x10, 0x6a, 0x68, 0x65, 0x40, 0x13, 0x6f, 0x9f, 0x28, 0xcb, 0x2b, 0x48,
	0xc3, 0x4d, 0x24, 0x83, 0xb3, 0x57, 0x77, 0x77, 0xef, 0x3f, 0x5f, 0xdc, 0x23, 0xe7, 0x90, 0xbc,
	0xb9, 0x7d, 0xf7, 0xe5, 0x22, 0x7a, 0x5d, 0x7f, 0x7d, 0xda, 0x49, 0xb7, 0x1d, 0xd7, 0x4c, 0xa8,
	0xbe, 0xea, 0x90, 0x9b, 0x41, 0xb5, 0x78, 0x78, 0x41, 0xfa, 0x7b, 0x57, 0x71, 0x2d, 0x2d, 0x9a,
	0x3d, 0x9a, 0xe3, 0x7b, 0x5a, 0xa7, 0x7e, 0x2d, 0xcf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2d,
	0xf8, 0xf2, 0x0f, 0x6c, 0x02, 0x00, 0x00,
}
