// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/judge/v1alpha1/policy.proto

package v1alpha1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A Judge policy.
type Policy struct {
	// The object resource name of the document, for example
	// `orn:judge-org:judge-service::policy/default_policy`.
	Orn string `protobuf:"bytes,1,opt,name=orn,proto3" json:"orn,omitempty"`
	// Name element specifies a user friendly name for the policy.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Description element specifies description/usage about the policy.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Document contains all statements for the policy.
	Document *Document `protobuf:"bytes,4,opt,name=document,proto3" json:"document,omitempty"`
	// Output only. The time at which the policy was created.
	CreateTime *timestamp.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// Output only. The time at which the document was last changed.
	//
	// This value is initally set to the `create_time` then increases
	// monotonically with each change to the policy.
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{0}
}

func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (m *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(m, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetOrn() string {
	if m != nil {
		return m.Orn
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *Policy) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Policy) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

// An Document.
type Document struct {
	// Version is the Statement version.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Statement contains a list of Statement.
	Statements           []*Statement `protobuf:"bytes,2,rep,name=statements,proto3" json:"statements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{1}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Document) GetStatements() []*Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

// An Statement.
type Statement struct {
	// The Effect element is required and specifies whether the statement
	// results in an allow or an explicit deny. Valid values for Effect are
	// Allow and Deny.
	Effect string `protobuf:"bytes,1,opt,name=effect,proto3" json:"effect,omitempty"`
	// The Action element describes the specific action or actions that will
	// be allowed or denied.
	Actions []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// The Resource element specifies the object or objects that the statement
	// covers.
	Resources            []string `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statement) Reset()         { *m = Statement{} }
func (m *Statement) String() string { return proto.CompactTextString(m) }
func (*Statement) ProtoMessage()    {}
func (*Statement) Descriptor() ([]byte, []int) {
	return fileDescriptor_187ca9f6326818cb, []int{2}
}

func (m *Statement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statement.Unmarshal(m, b)
}
func (m *Statement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statement.Marshal(b, m, deterministic)
}
func (m *Statement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statement.Merge(m, src)
}
func (m *Statement) XXX_Size() int {
	return xxx_messageInfo_Statement.Size(m)
}
func (m *Statement) XXX_DiscardUnknown() {
	xxx_messageInfo_Statement.DiscardUnknown(m)
}

var xxx_messageInfo_Statement proto.InternalMessageInfo

func (m *Statement) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *Statement) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *Statement) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func init() {
	proto.RegisterType((*Policy)(nil), "judge.api.v1alpha1.Policy")
	proto.RegisterType((*Document)(nil), "judge.api.v1alpha1.Document")
	proto.RegisterType((*Statement)(nil), "judge.api.v1alpha1.Statement")
}

func init() { proto.RegisterFile("api/judge/v1alpha1/policy.proto", fileDescriptor_187ca9f6326818cb) }

var fileDescriptor_187ca9f6326818cb = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x6a, 0xe3, 0x30,
	0x10, 0x26, 0x71, 0xd6, 0x1b, 0x8f, 0x2f, 0x8b, 0x0e, 0x8b, 0x08, 0x59, 0x62, 0x72, 0xca, 0x49,
	0xde, 0x64, 0x2f, 0x0b, 0xcb, 0x5e, 0x4a, 0x1f, 0xa0, 0xb8, 0x3d, 0xb5, 0x87, 0xa2, 0xc8, 0x13,
	0x47, 0x6d, 0x6c, 0x09, 0x49, 0x0e, 0xf4, 0xde, 0x07, 0x2f, 0x92, 0x7f, 0x1a, 0x68, 0xa1, 0x37,
	0xcd, 0xf7, 0xa3, 0x99, 0x6f, 0x18, 0x58, 0x71, 0x2d, 0xf3, 0xa7, 0xb6, 0xac, 0x30, 0x3f, 0x6f,
	0xf9, 0x49, 0x1f, 0xf9, 0x36, 0xd7, 0xea, 0x24, 0xc5, 0x0b, 0xd3, 0x46, 0x39, 0x45, 0x48, 0x20,
	0x19, 0xd7, 0x92, 0x0d, 0x82, 0xc5, 0xaa, 0x52, 0xaa, 0x3a, 0x61, 0x1e, 0x14, 0xfb, 0xf6, 0x90,
	0x3b, 0x59, 0xa3, 0x75, 0xbc, 0xd6, 0x9d, 0x69, 0xfd, 0x3a, 0x85, 0xf8, 0x26, 0xfc, 0x42, 0x7e,
	0x40, 0xa4, 0x4c, 0x43, 0x27, 0xd9, 0x64, 0x93, 0x14, 0xfe, 0x49, 0x08, 0xcc, 0x1a, 0x5e, 0x23,
	0x9d, 0x06, 0x28, 0xbc, 0x49, 0x06, 0x69, 0x89, 0x56, 0x18, 0xa9, 0x9d, 0x54, 0x0d, 0x8d, 0x02,
	0x75, 0x09, 0x91, 0xbf, 0x30, 0x2f, 0x95, 0x68, 0x6b, 0x6c, 0x1c, 0x9d, 0x65, 0x93, 0x4d, 0xba,
	0x5b, 0xb2, 0x8f, 0xa3, 0xb1, 0xeb, 0x5e, 0x53, 0x8c, 0x6a, 0xf2, 0x0f, 0x52, 0x61, 0x90, 0x3b,
	0x7c, 0xf4, 0x63, 0xd2, 0x6f, 0xc1, 0xbc, 0x60, 0x5d, 0x06, 0x36, 0x64, 0x60, 0x77, 0x43, 0x86,
	0x02, 0x3a, 0xb9, 0x07, 0xbc, 0xb9, 0xd5, 0xe5, 0x68, 0x8e, 0xbf, 0x36, 0x77, 0x72, 0x0f, 0xac,
	0x05, 0xcc, 0x87, 0x79, 0x08, 0x85, 0xef, 0x67, 0x34, 0xd6, 0xa7, 0xeb, 0x76, 0x31, 0x94, 0xe4,
	0x3f, 0x80, 0x75, 0xdc, 0xa1, 0x97, 0x59, 0x3a, 0xcd, 0xa2, 0x4d, 0xba, 0xfb, 0xf5, 0x59, 0xb6,
	0xdb, 0x41, 0x55, 0x5c, 0x18, 0xd6, 0x0f, 0x90, 0x8c, 0x04, 0xf9, 0x09, 0x31, 0x1e, 0x0e, 0x28,
	0x5c, 0xdf, 0xa4, 0xaf, 0x7c, 0x77, 0x2e, 0xfc, 0x1e, 0xbb, 0x06, 0x49, 0x31, 0x94, 0x64, 0x09,
	0x89, 0x41, 0xab, 0x5a, 0x23, 0xd0, 0xd2, 0x28, 0x70, 0xef, 0xc0, 0xd5, 0xee, 0xfe, 0x77, 0x25,
	0xdd, 0xb1, 0xdd, 0x33, 0xa1, 0xea, 0xbc, 0x42, 0x6e, 0x1a, 0x55, 0x62, 0x7f, 0x30, 0xfa, 0xb9,
	0xca, 0xb9, 0x96, 0x16, 0xcd, 0x19, 0xcd, 0x78, 0x3e, 0xfb, 0x38, 0x6c, 0xe5, 0xcf, 0x5b, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x4d, 0x56, 0x7c, 0xde, 0x5b, 0x02, 0x00, 0x00,
}
